services:
  backend:
    build:  ./esg_backend
    ports: 
    - "5001:5001"
    volumes: 
    - ./esg_backend:/app/src
    environment: 
      FLASK_ENV: development
      FLASK_APP: app.py
      FLASK_DEBUG: 1
      PYTHONDONTWRITEBYTECODE: 1
      DATA_DIR: /app/src/api/data
      DB_PATH: /app/src/api/data/esg_scores.db
      DB_MANAGE_PATH: /app/src/utils/data_utils/db_manage.py
    command: gunicorn -b 0.0.0.0:5001 app:app
  frontend:
    build: ./esg_frontend
    ports: 
      - "3000:3000"
    volumes: 
      - ./esg_frontend:/app/frontend
    command: npm start
    depends_on: 
      - backend